# Generated by Django 3.1.2 on 2020-10-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
    ]
